import urllib.request
import urllib.parse
import json
import re
import time
import os

LUA_IN = "/tmp/out/text.lua"
LUA_OUT = "mods/full_spanish_translation/main.lua"

def translate_batch(texts, target_lang="es"):
    # Replace tokens
    batch_tokens = []
    placeholder_texts = []
    
    for text in texts:
        tokens = re.findall(r"(\{[^}]+\}|\\n|\\v|\\f|\\r)", text)
        batch_tokens.append(tokens)
        
        ph_text = text
        for i, token in enumerate(tokens):
            ph_text = ph_text.replace(token, f" __TOK{i}__ ")
        placeholder_texts.append(ph_text)

    # Join with a unique delimiter that Google Translate won't usually mangle
    delimiter = " \n\n###\n\n "
    joined_text = delimiter.join(placeholder_texts)
    
    url = "https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=" + target_lang + "&dt=t&q=" + urllib.parse.quote(joined_text)
    
    retries = 3
    for attempt in range(retries):
        try:
            req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
            with urllib.request.urlopen(req) as response:
                data = json.loads(response.read().decode('utf-8'))
                translated_joined = "".join([sentence[0] for sentence in data[0] if sentence[0]])
                
                # Split back
                translated_texts = re.split(r'\s*###\s*', translated_joined)
                
                if len(translated_texts) != len(texts):
                    print(f"Warning: Batch size mismatch after translation. Expected {len(texts)}, got {len(translated_texts)}.")
                    return texts
                
                final_translations = []
                for t_text, tokens in zip(translated_texts, batch_tokens):
                    for i, token in enumerate(tokens):
                        t_text = t_text.replace(f"__TOK{i}__", token)
                        t_text = t_text.replace(f" __TOK{i}__ ", token)
                        t_text = t_text.replace(f"__TOK{i}__ ", token)
                        t_text = t_text.replace(f" __TOK{i}__", token)
                        t_text = t_text.replace(f" {token}", token)
                        t_text = t_text.replace(f"{token} ", token)
                    final_translations.append(t_text.strip())
                    
                return final_translations
                
        except Exception as e:
            print(f"Translation failed (attempt {attempt+1}/{retries}): {e}")
            time.sleep(3 ** (attempt + 1)) # Exponential backoff
            
    return texts

def main():
    print("Starting batched translation...")
    
    with open(LUA_IN, "r", encoding="utf-8") as f:
        content = f.read()
        
    pattern = re.compile(r'^\s*([a-zA-Z0-9_]+)\s*=\s*"(.*)",?$', re.MULTILINE)
    matches = pattern.findall(content)
    
    print(f"Found {len(matches)} strings to translate.")
    
    out_lines = [
        "return function(mod)",
        "  -- Automated Spanish Translation generated by translation script",
        "  mod.log:info('Loaded automated Spanish translation')",
        ""
    ]
    
    batch_size = 20
    total = len(matches)
    
    for i in range(0, total, batch_size):
        batch = matches[i:i+batch_size]
        keys = [item[0] for item in batch]
        values = [item[1].replace('\\"', '"') for item in batch]
        
        print(f"Translating batch {i//batch_size + 1}/{(total//batch_size) + 1}...")
        
        translated_values = translate_batch(values)
        
        for key, trans_val in zip(keys, translated_values):
            trans_val_escaped = trans_val.replace('"', '\\"')
            out_lines.append(f'  mod.content.text:override("{key}", "{trans_val_escaped}")')
            
        # Write periodically so we don't lose progress
        with open(LUA_OUT, "w", encoding="utf-8") as f:
            f.write("\n".join(out_lines) + "\nend\n")
            
        time.sleep(1.5) # Rate limiting
        
    print(f"Successfully wrote {LUA_OUT}")

if __name__ == "__main__":
    main()
